### ISSUE TITLE
Firefox vertical margins on "teasers"

### ISSUE THREAD

**Issue by hcpss-banderson** [HCPSS/story-strong#1]
Vertical padding and margin is not being calculated properly on Firefox for the "teaser" cards:

![margins](https://cloud.githubusercontent.com/assets/10929134/25901862/fdb910a0-3565-11e7-9355-c7224e4c21ad.png)

Using FF 53.0.2 on macOS.

**Comment by hcpss-banderson** [comment]
If I understand [this issue from mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=958714), they consider this to work as designed.

**Comment by hcpss-vincevince1006** [comment]
Fixed with [eabf8d8](https://github.com/hcpss-vincevince1006/story-strong/commit/eabf8d8ccaf9d84c996b2276483973ac3cd0a7fb). Susy was set to generate percentages when calculating margins/padding. Set `margin-bottom` to a `vw` value and `em` for fallback, and `padding-bottom` to an `em` value. Slight difference in gutter look/feel between chrome and FF, but it's not too bad. Thanks for pointing this out! Might see if Modernizr has a fix for this in the future.
